# Generated by Django 6.0.3 on 2026-03-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='empresa',
        ),
        migrations.AddField(
            model_name='camion',
            name='patente',
            field=models.CharField(default='provisoria', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='nombre',
            field=models.CharField(default='provisorio', max_length=100, verbose_name='Nombre de la Sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
