# Generated by Django 6.0.3 on 2026-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_remove_sede_empresa_camion_patente_sede_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camion',
            options={'verbose_name': 'Camión', 'verbose_name_plural': 'Camiones'},
        ),
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name': 'Chofer', 'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
